load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "xxhash",
    srcs = ["xxhash.c"] + select({
        "@platforms//cpu:x86_64": ["xxh_x86dispatch.c"],
        "//conditions:default": [],
    }),
    hdrs = [
        "xxh3.h",
        "xxhash.h",
    ] + select({
        "@platforms//cpu:x86_64": ["xxh_x86dispatch.h"],
        "//conditions:default": [],
    }),
    local_defines = select({
        "@platforms//cpu:x86_64": ["XXHSUM_DISPATCH=1"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
)
